#*****************************************************************************
#
#  System        : 
#  Module        : 
#  Object Name   : $RCSfile$
#  Revision      : $Revision$
#  Date          : $Date$
#  Author        : $Author$
#  Created By    : Robert Heller
#  Created       : 2026-02-23 12:02:35
#  Last Modified : <260225.0824>
#
#  Description	
#
#  Notes
#
#  History
#	
#*****************************************************************************
#
#    Copyright (C) 2026  Robert Heller D/B/A Deepwoods Software
#			51 Locke Hill Road
#			Wendell, MA 01379-9728
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# 
#
#*****************************************************************************




import FreeCAD as App
import Part, TechDraw, Mesh, Import
from FreeCAD import Base

import os
import sys
sys.path.append(os.path.dirname(__file__))

def debug(fmt,*args):
    print(fmt % args,file=sys.stderr)

class Board(object):
    __Width = 118.21
    __Length = 105.51
    __HoleSpaceW = 110.49
    __HoleSpaceL = 97.79
    __HoleDiameter = 3.2
    __BoardThick = 1.6
    __Color = (0.0,1.0,0.0)
    #__STL = os.path.join(os.path.dirname(__file__),"PocketBeagleCommandStation_SMD.stl")
    @classmethod
    def BoardSize(cls):
        return (cls.__Width,cls.__Length)
    @classmethod
    def BoardThick(cls):
        return cls.__BoardThick
    @classmethod
    def MountingHoleDiameter(cls):
        return cls.__HoleDiameter
    @classmethod 
    def HoleOffsets(cls):
        hL = (cls.__Width/2)-(cls.__HoleSpaceW/2)
        hR = (cls.__Width/2)+(cls.__HoleSpaceW/2)
        hU = (cls.__Length/2)-(cls.__HoleSpaceL/2)
        hD = (cls.__Length/2)+(cls.__HoleSpaceL/2)
        return [(hL,hU), (hR,hU), (hL, hD), (hR, hD)]
    @property
    def HoleCenters(self):
        holeOffsets = Board.HoleOffsets()
        result = list()
        for hO in holeOffsets:
            hX, hY = hO
            result.append(self.origin.add(Base.Vector(hX,hY,0)))
        return result
    @classmethod
    def HoleDiameter(cls):
        return cls.__HoleDiameter    
    def __init__(self,name,origin=Base.Vector(0,0,0)):
        self.name = name
        if not isinstance(origin,Base.Vector):
            raise RuntimeError("origin is not a Vector!")
        self.origin = origin
        board = Part.makePlane(self.__Width,self.__Length,self.origin)\
                .extrude(Base.Vector(0,0,self.__BoardThick))
        for hO in self.HoleCenters:
            hole = Part.makeCylinder(self.__HoleDiameter/2,self.__BoardThick,hO)
            board = board.cut(hole)
        self.board = board
        #board3d = Mesh.read(self.__STL)
        #board3d.translate(self.origin.x,self.origin.y,self.origin.z)
        #self.board3d = board3d
        
    def show(self,doc=None):
        if doc==None:
            doc = App.activeDocument()
        obj = doc.addObject("Part::Feature",self.name)
        obj.Shape = self.board
        obj.Label=self.name
        obj.ViewObject.ShapeColor=self.__Color
    #def show3D(self,doc=None):
    #    if doc==None:
    #        doc = App.activeDocument()
    #    obj = doc.addObject("Mesh::Feature",self.name+"_3D")
    #    obj.Mesh = self.board3d
    #    obj.Label = self.name+"_3D"

class Case(object):
    __BoardSize = Board.BoardSize()
    __BoardThick = Board.BoardThick()
    __BoardMHoleDiameter = Board.MountingHoleDiameter()
    __WallThick = 2.54
    __SpaceUnderBoard = 5.08
    __SpaceAboveBoard = 27.4-2.14
    __MountTabWidth = .375*25.4
    __MountTabLength = .5*25.4
    __MountTabHoleDiameter = 3.2
    @property
    def CaseWidth(self):
        w,l = self.__BoardSize
        return w+(self.__WallThick*2)
    @property
    def CaseLength(self):
        w,l = self.__BoardSize
        return l+(self.__WallThick*2)
    @property
    def MountTabCY1(self):
        return self.CaseLength*.25
    @property
    def MountTabCY2(self):
        return self.CaseLength*.75
    @property
    def CaseBottomHeight(self):
        return self.__WallThick+self.__SpaceUnderBoard+self.__BoardThick
    @property
    def CaseTopHeight(self):
        return self.__WallThick+self.__SpaceAboveBoard+(self.__WallThick/2)
    def __bottom(self):
        bot = Part.makePlane(self.CaseWidth,self.CaseLength,self.origin) \
            .extrude(Base.Vector(0,0,self.__WallThick))
        bot = bot.fuse(
            Part.makePlane(self.CaseBottomHeight,self.CaseLength,
                           self.origin.add(Base.Vector(0,self.CaseLength,0)),
                           Base.Vector(1,0,0)).extrude(Base.Vector(self.__WallThick,0,0))
        )
        bot = bot.fuse(
            Part.makePlane(self.CaseBottomHeight,self.CaseLength,
                           self.origin.add(Base.Vector(self.CaseWidth-self.__WallThick,
                                                       self.CaseLength,0)),
                           Base.Vector(1,0,0)).extrude(Base.Vector(self.__WallThick,0,0))
        )
        bot = bot.fuse(
            Part.makePlane(self.CaseBottomHeight,self.CaseWidth,
                           self.origin,
                           Base.Vector(0,1,0)).extrude(Base.Vector(0,self.__WallThick,0))
        )
        bot = bot.fuse(
            Part.makePlane(self.CaseBottomHeight,self.CaseWidth,
                           self.origin.add(Base.Vector(0,self.CaseLength-self.__WallThick,0)),
                           Base.Vector(0,1,0)).extrude(Base.Vector(0,self.__WallThick,0))
        )
        temp = Part.makePlane(self.__WallThick,self.__WallThick,self.origin,
                              Base.Vector(0,1,0))\
                .extrude(Base.Vector(0,self.CaseLength,0))
        offset = Base.Vector(self.__WallThick,0,self.__WallThick)
        rod = Part.makeCylinder(self.__WallThick,self.CaseLength,
                                self.origin.add(offset),Base.Vector(0,1,0))
        bot = bot.cut(temp.cut(rod))
        temp = Part.makePlane(self.__WallThick,self.__WallThick,
                              self.origin.add(Base.Vector(self.CaseWidth-self.__WallThick,0,0)),
                              Base.Vector(0,1,0))\
                .extrude(Base.Vector(0,self.CaseLength,0))
        offset = Base.Vector(self.CaseWidth-self.__WallThick,0,self.__WallThick)
        rod = Part.makeCylinder(self.__WallThick,self.CaseLength,
                                self.origin.add(offset),Base.Vector(0,1,0))
        bot = bot.cut(temp.cut(rod))
        temp = Part.makePlane(self.__WallThick,self.__WallThick,
                              self.origin.add(Base.Vector(0,self.__WallThick,0)),
                              Base.Vector(1,0,0)).extrude(Base.Vector(self.CaseWidth,0,0))
        offset = Base.Vector(0,self.__WallThick,self.__WallThick)
        rod = Part.makeCylinder(self.__WallThick,self.CaseWidth,
                                self.origin.add(offset),Base.Vector(1,0,0))
        bot = bot.cut(temp.cut(rod))
        temp = Part.makePlane(self.__WallThick,self.__WallThick,
                              self.origin.add(Base.Vector(0,self.CaseLength,0)),
                              Base.Vector(1,0,0)).extrude(Base.Vector(self.CaseWidth,0,0))
        offset = Base.Vector(0,self.CaseLength-self.__WallThick,self.__WallThick)
        rod = Part.makeCylinder(self.__WallThick,self.CaseWidth,
                                self.origin.add(offset),Base.Vector(1,0,0))
        bot = bot.cut(temp.cut(rod))
        temp = Part.makePlane(self.__WallThick,self.__WallThick,
                              self.origin).extrude(Base.Vector(0,0,self.CaseBottomHeight))
        rod = Part.makeCylinder(self.__WallThick,self.CaseBottomHeight,
                                self.origin.add(Base.Vector(self.__WallThick,self.__WallThick,0)))
        self.t = temp
        self.r = rod
        bot = bot.cut(temp.cut(rod))
        temp = Part.makePlane(self.__WallThick,self.__WallThick,
                              self.origin.add(Base.Vector(0,self.CaseLength-self.__WallThick,0))
                              ).extrude(Base.Vector(0,0,self.CaseBottomHeight))
        rod = Part.makeCylinder(self.__WallThick,self.CaseBottomHeight,
                                self.origin.add(Base.Vector(self.__WallThick,
                                                            self.CaseLength-self.__WallThick,0)))
        self.t = temp
        self.r = rod
        bot = bot.cut(temp.cut(rod))
        temp = Part.makePlane(self.__WallThick,self.__WallThick,
                              self.origin.add(Base.Vector(self.CaseWidth-self.__WallThick,0,0))
                              ).extrude(Base.Vector(0,0,self.CaseBottomHeight))
        rod = Part.makeCylinder(self.__WallThick,self.CaseBottomHeight,
                                self.origin.add(Base.Vector(self.CaseWidth-self.__WallThick,self.__WallThick,0)))
        self.t = temp
        self.r = rod
        bot = bot.cut(temp.cut(rod))
        temp = Part.makePlane(self.__WallThick,self.__WallThick,
                              self.origin.add(Base.Vector(self.CaseWidth-self.__WallThick,
                                                          self.CaseLength-self.__WallThick,0))
                              ).extrude(Base.Vector(0,0,self.CaseBottomHeight))
        rod = Part.makeCylinder(self.__WallThick,self.CaseBottomHeight,
                                self.origin.add(Base.Vector(self.CaseWidth-self.__WallThick,
                                                            self.CaseLength-self.__WallThick,0)))
        self.t = temp
        self.r = rod
        bot = bot.cut(temp.cut(rod))

        taborigin = self.origin.add(Base.Vector(-self.__MountTabLength,
                                                self.MountTabCY1-(self.__MountTabWidth/2),
                                                0))
        tab = Part.makePlane(self.__MountTabLength+self.__WallThick,
                             self.__MountTabWidth,taborigin)\
                .extrude(Base.Vector(0,0,self.__WallThick))
        bot = bot.fuse(tab)
        taborigin = self.origin.add(Base.Vector(-self.__MountTabLength,
                                                self.MountTabCY2-(self.__MountTabWidth/2),
                                                0))
        tab = Part.makePlane(self.__MountTabLength+self.__WallThick,
                             self.__MountTabWidth,taborigin)\
                .extrude(Base.Vector(0,0,self.__WallThick))
        bot = bot.fuse(tab)
        taborigin = self.origin.add(Base.Vector(self.CaseWidth-self.__WallThick,
                                                self.MountTabCY1-(self.__MountTabWidth/2),
                                                0))
        tab = Part.makePlane(self.__MountTabLength+self.__WallThick,
                             self.__MountTabWidth,taborigin)\
                .extrude(Base.Vector(0,0,self.__WallThick))
        bot = bot.fuse(tab)
        taborigin = self.origin.add(Base.Vector(self.CaseWidth-self.__WallThick,
                                                self.MountTabCY2-(self.__MountTabWidth/2),
                                                0))
        tab = Part.makePlane(self.__MountTabLength+self.__WallThick,
                             self.__MountTabWidth,taborigin)\
                .extrude(Base.Vector(0,0,self.__WallThick))
        bot = bot.fuse(tab)
        return bot
    def __init__(self,name,origin=Base.Vector(0,0,0)):
        self.name = name
        if not isinstance(origin,Base.Vector):
            raise RuntimeError("origin is not a Vector!")
        self.origin = origin
        self.bottom = self.__bottom()
    def show(self,doc=None):
        if doc==None:
            doc = App.activeDocument()
        obj = doc.addObject("Part::Feature",self.name+"_bottom")
        obj.Shape = self.bottom
        obj.Label=self.name+"_bottom"
        obj.ViewObject.ShapeColor=(0.5,0.5,0.5)
        #obj = doc.addObject("Part::Feature",self.name+"_r")
        #obj.Shape = self.r
        #obj.ViewObject.ShapeColor=(1.0,0.0,0.0)
        #obj = doc.addObject("Part::Feature",self.name+"_t")
        #obj.Shape = self.t
        #obj.ViewObject.ShapeColor=(0.0,1.0,0.0)
        
        
if __name__ == '__main__':
    if "RevCBoardCase" in App.listDocuments().keys():
        App.closeDocument("RevCBoardCase")
    doc = App.newDocument("RevCBoardCase")
    doc = App.activeDocument()
    case = Case("case")
    case.show(doc)
    Gui.activeDocument().activeView().viewTop()
    Gui.SendMsgToActiveView("ViewFit")
    
